INSERT INTO alineacion_unidad (unidad_polimero_unidad, alineacion_polimero_alineacion)
 VALUES     ('U. SNF',	    'U. SNF'),
			('U. BASF',	'U. BASF'),
			('Desh. U1',	'Desh. U1'),
			('Desh. U2',	'Desh. U2'),
			('Lub. UA',	'Lub.'),
			('Lub. UB',	'Lub.'),
			('Esp. U1',	'Esp. - Desh. U1'),
			('Esp. U2',	'Esp. - Desh. U1'),
			('Desh. U1',	'Esp. - Desh. U1'),
			('Esp. U1',	'Esp. -Desh.'),
			('Esp. U2',	'Esp. -Desh.'),
			('Desh. U1',	'Esp. -Desh.'),
			('Desh. U2',	'Esp. -Desh.'),
			('Desh. U1',	'Desh. U1-U2'),
			('Desh. U2',	'Desh. U1-U2'),
			('Desh. U1',	'Desh. U1 - Lub.'),
			('Lub. UA',	'Desh. U1 - Lub.'),
			('Lub. UB',	'Desh. U1 - Lub.'),
			('Desh. U2',	'Desh. U2 - Lub.'),
			('Lub. UA',	'Desh. U2 - Lub.'),
			('Lub. UB',	'Desh. U2 - Lub.'),
			('Desh. U1',	'Desh. - Lub'),
			('Desh. U2',	'Desh. - Lub'),
			('Lub. UA',	'Desh. - Lub'),
			('Lub. UB',	'Desh. - Lub'),
			('Esp. U1',	'Esp. U1 - Desh. U1'),
			('Desh. U1',	'Esp. U1 - Desh. U1'),
			('Esp. U1',	'Todas Unidas'),
			('Esp. U2',	'Todas Unidas'),
			('Desh. U1',	'Todas Unidas'),
			('Desh. U2',	'Todas Unidas'),
			('Lub. UA',	'Todas Unidas'),
			('Lub. UB',	'Todas Unidas'),
			('U. SNF',	'Todas Unidas'),
			('U. BASF',	'Todas Unidas')
;